variable "host" { }
variable "username" { }
variable "password" { }
variable "client_certificate" { }
variable "client_key" { }
variable "cluster_ca_certificate" { }
variable "docker_username" { }
variable "docker_password" { }
variable "kubernetes_secret" { }